apiVersion: apps/v1
kind: Deployment

metadata:
  name: tts-deployment

spec:
  replicas: 3

  selector:
    matchLabels:
      app: tts

  template:
    metadata:
      labels:
        app: tts

    spec:
      containers:
        - name: tts-container
          image: arshen00r/text-to-speech:v1
          ports:
            - containerPort: 80